import assert from 'node:assert/strict';import test from 'node:test';import {randomUUID} from 'node:crypto';import pg from 'pg';
const url=process.env.FAIRGROUND_TEST_DB_URL;if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Isolated local database required');
const db=new pg.Client({connectionString:url});await db.connect();const tid='5ff73034-1747-4b9e-874a-6fe19fa68ac1',otherTid=randomUUID(),[referee,admin]=[randomUUID(),randomUUID()],teams=Array.from({length:8},randomUUID),sources=Array.from({length:4},randomUUID);let other;
const as=async(c,actor=referee)=>{await c.query('reset session authorization');await c.query('set session authorization authenticated');await c.query("select set_config('request.jwt.claim.sub',$1,false)",[actor]);};
const rpc=async(c,matchId,kind,payload={},id=randomUUID())=>(await c.query('select apply_match_recording_operation($1,$2,$3,$4) r',[id,matchId,kind,payload])).rows[0].r;
const generated=async()=>{await db.query('reset session authorization');return(await db.query('select * from matches where tournament_id=$1 and round between 17 and 20 order by round',[tid])).rows;};
const reset=async()=>{await db.query('reset session authorization');await db.query('begin');await db.query('delete from matches where tournament_id=$1 and round between 17 and 20',[tid]);await db.query("update matches set status='live',stats_applied=false,is_running=false where id=any($1::uuid[])",[[sources[2],sources[3]]]);await db.query('commit');await as(db);};
const expected=[[teams[1],teams[2]],[teams[0],teams[3]],[teams[4],teams[6]],[teams[5],teams[7]]];
const assertReady=async()=>{const rows=await generated();assert.equal(rows.length,4);for(let i=0;i<4;i++){const r=rows[i];assert.equal(r.round,17+i);assert.deepEqual([r.home_team_id,r.away_team_id],expected[i]);assert.equal(r.home_team_name,'합성 팀 '+teams.indexOf(expected[i][0]));assert.equal(r.away_team_name,'합성 팀 '+teams.indexOf(expected[i][1]));assert.equal(r.group_id,null);assert.equal(r.status,'scheduled');assert.equal(r.current_half,1);assert.equal(r.elapsed_seconds,0);assert.equal(r.is_running,false);assert.equal(r.stats_applied,false);assert.equal(r.home_score,0);assert.equal(r.away_score,0);assert.equal(r.home_shootout_score,null);assert.equal(r.away_shootout_score,null);assert.equal(r.scheduled_at.toISOString(),['2026-10-03T06:20:00.000Z','2026-10-03T06:40:00.000Z','2026-10-03T07:00:00.000Z','2026-10-03T07:20:00.000Z'][i]);}return rows;};
try{
 await db.query('begin');for(const id of [referee,admin])await db.query('insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)',[id,`${id}@synthetic.invalid`,{name:'합성 대진 검수',portrait_consent:true}]);await db.query("select set_config('app.in_end_match','1',true)");await db.query("update profiles set role='referee',is_approved=true where id=$1",[referee]);await db.query("update profiles set role='admin',is_approved=true where id=$1",[admin]);for(let i=0;i<8;i++)await db.query('insert into teams(id,name,is_approved) values($1,$2,true)',[teams[i],'합성 팀 '+i]);await db.query('insert into tournaments(id,name) values($1,$2),($3,$4)',[tid,'합성 자동 대진',otherTid,'합성 다른 대회']);for(let i=0;i<4;i++)await db.query("insert into matches(id,tournament_id,round,home_team_id,away_team_id,home_team_name,away_team_name,status,is_running,home_score,away_score) values($1,$2,$3,$4,$5,$6,$7,'live',false,$8,$9)",[sources[i],tid,13+i,teams[2*i],teams[2*i+1],'합성 팀 '+(2*i),'합성 팀 '+(2*i+1),[4,0,0,0][i],[0,0,2,1][i]]);await db.query('commit');await as(db);other=new pg.Client({connectionString:url});await other.connect();await as(other,admin);
 await test('private automation functions grant no API role execution',async()=>{for(const role of ['anon','authenticated','service_role'])for(const fn of ['ensure_cup_rank_fixtures(uuid)','ensure_cup_rank_fixtures_after_result()'])assert.equal((await db.query('select has_function_privilege($1,$2,$3) allowed',[role,'public.'+fn,'EXECUTE'])).rows[0].allowed,false);});
 await test('first three completed sources create no future fixtures',async()=>{await rpc(db,sources[0],'end');await rpc(db,sources[1],'shootout',{homeScore:0,awayScore:1,_shootoutHomeBefore:-1,_shootoutAwayBefore:-1});await rpc(db,sources[1],'end');await rpc(db,sources[2],'end');assert.equal((await generated()).length,0);await as(db);});
 let finalOperation;
 await test('16 finalization automatically creates exactly four correctly seeded fixtures',async()=>{finalOperation=randomUUID();await rpc(db,sources[3],'end',{},finalOperation);await assertReady();await as(db);});
 await test('lost-response finalization retry and repeated owner ensure preserve all existing fixture rows',async()=>{const before=await generated();await as(db);await rpc(db,sources[3],'end',{},finalOperation);await db.query('reset session authorization');for(let i=0;i<2;i++){const r=(await db.query('select ensure_cup_rank_fixtures($1) r',[tid])).rows[0].r;assert.deepEqual(r.createdMatchIds,[]);}assert.deepEqual(await generated(),before);await as(db);});
 await test('unique scoped round index rejects a duplicate manual fixture',async()=>{const r=(await generated())[0];await assert.rejects(db.query('insert into matches(tournament_id,round,home_team_name,away_team_name) values($1,$2,$3,$4)',[tid,r.round,'중복 합성 홈','중복 합성 원정']),/matches_cup_rank_round_unique/);await as(db);});
 await test('preexisting scheduled or live future matches are never overwritten',async()=>{await db.query('reset session authorization');await db.query("update matches set status='live',is_running=true,elapsed_seconds=77 where tournament_id=$1 and round=17",[tid]);const before=await generated();await db.query('select ensure_cup_rank_fixtures($1)',[tid]);assert.deepEqual(await generated(),before);await as(db);});
 await test('16 ending before 15 waits and 15 ending later creates the four fixtures',async()=>{await reset();await rpc(db,sources[3],'end');assert.equal((await generated()).length,0);await as(db);await rpc(db,sources[2],'end');await assertReady();await as(db);});
 await test('two independent approved finalizers concurrently ending 15 and 16 do not deadlock or duplicate',async()=>{await reset();await Promise.all([rpc(db,sources[2],'end'),rpc(other,sources[3],'end')]);await assertReady();await as(db);});
 await test('finished tied source without shootout waits, and a later saved result creates fixtures',async()=>{await db.query('reset session authorization');await db.query('begin');await db.query('delete from matches where tournament_id=$1 and round between 17 and 20',[tid]);await db.query('update matches set home_shootout_score=null,away_shootout_score=null where id=$1',[sources[1]]);await db.query('commit');assert.equal((await generated()).length,0);const waiting=(await db.query('select ensure_cup_rank_fixtures($1) r',[tid])).rows[0].r;assert.equal(waiting.status,'waiting_for_shootout');await as(db);await rpc(db,sources[1],'shootout',{homeScore:0,awayScore:1,_shootoutHomeBefore:-1,_shootoutAwayBefore:-1});await assertReady();await as(db);});
 await test('another tournament finalization changes none of this tournament future fixtures',async()=>{const before=await generated();const otherMatch=randomUUID();await db.query("insert into matches(id,tournament_id,round,home_team_id,away_team_id,home_team_name,away_team_name,status,home_score,away_score) values($1,$2,16,$3,$4,'다른 합성 홈','다른 합성 원정','live',1,0)",[otherMatch,otherTid,teams[0],teams[1]]);await as(db);await rpc(db,otherMatch,'end');await db.query('reset session authorization');assert.equal((await db.query('select count(*)::int n from matches where tournament_id=$1 and round between 17 and 20',[otherTid])).rows[0].n,0);assert.deepEqual(await generated(),before);await assert.rejects(db.query('select ensure_cup_rank_fixtures($1)',[otherTid]),/limited to this cup/);await as(db);});
 await test('fallback owner ensure when all sources were finished before trigger installation creates only missing fixtures',async()=>{await db.query('reset session authorization');await db.query('delete from matches where tournament_id=$1 and round between 17 and 20',[tid]);const before=(await db.query('select * from matches where tournament_id=$1 and round between 13 and 16 order by round',[tid])).rows;const r=(await db.query('select ensure_cup_rank_fixtures($1) r',[tid])).rows[0].r;assert.equal(r.createdMatchIds.length,4);await assertReady();assert.deepEqual((await db.query('select * from matches where tournament_id=$1 and round between 13 and 16 order by round',[tid])).rows,before);await as(db);});
}finally{await db.query('reset session authorization');await db.end();if(other)await other.end();}
