import type { Badge } from "@/types";

export const BADGES: Badge[] = [
  // ===== 필드 선수 뱃지 =====
  {
    id: "hat_trick",
    name: "해트트릭",
    icon: "⚽",
    imageUrl: "/images/badges/hat_trick.png?v=7",
    description: "한 경기에서 3골 이상",
    unlockCondition: "한 경기 3골",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "first_goal",
    name: "첫골",
    icon: "⚽",
    imageUrl: "/images/badges/first_goal.png?v=6",
    description: "공식 경기 첫 득점",
    unlockCondition: "골 1회 기록",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "golden_boot",
    name: "득점왕",
    icon: "👟",
    imageUrl: "/images/badges/golden_boot.png?v=6",
    description: "시즌 최다 득점",
    unlockCondition: "시즌 득점 1위",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "playmaker",
    name: "플레이메이커",
    icon: "👑",
    imageUrl: "/images/badges/playmaker.png?v=6",
    description: "시즌 어시스트 10개 달성",
    unlockCondition: "통산 어시스트 10회",
    maxProgress: 10,
    category: "field",
  },
  {
    id: "assist_king",
    name: "도움왕",
    icon: "🅰️",
    imageUrl: "/images/badges/assist_king.png?v=6",
    description: "시즌 최다 어시스트",
    unlockCondition: "시즌 어시스트 1위",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "fair_play",
    name: "페어플레이",
    icon: "🤝",
    imageUrl: "/images/badges/fair_play.png?v=6",
    description: "시즌 무경고 달성",
    unlockCondition: "시즌 무경고",
    category: "field",
  },
  {
    id: "iron_man",
    name: "철인",
    icon: "💪",
    imageUrl: "/images/badges/iron_man.png?v=6",
    description: "시즌 전 경기 출전",
    unlockCondition: "시즌 전 경기 출전",
    maxProgress: 20,
    category: "field",
  },
  {
    id: "mvp",
    name: "MVP",
    icon: "🏆",
    imageUrl: "/images/badges/mvp.png?v=6",
    description: "MOM 5회 달성",
    unlockCondition: "MOM 5회",
    maxProgress: 5,
    category: "field",
  },
  {
    id: "fair_eye",
    name: "공정한 눈",
    icon: "⚖️",
    imageUrl: "/images/badges/fair_eye.png?v=6",
    description: "공정한 판정 유지",
    unlockCondition: "오심률 0%",
    maxProgress: 1,
    category: "referee",
  },
  {
    id: "debut",
    name: "데뷔전",
    icon: "🌟",
    imageUrl: "/images/badges/debut.png?v=6",
    description: "공식 경기 첫 출전",
    unlockCondition: "첫 경기 출전",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "loyalty",
    name: "원클럽맨",
    icon: "🏠",
    imageUrl: "/images/badges/loyalty.png?v=6",
    description: "같은 팀 3시즌 연속 활동",
    unlockCondition: "동일 팀 3시즌",
    maxProgress: 3,
    category: "field",
  },
  {
    id: "captain",
    name: "캡틴",
    icon: "©️",
    imageUrl: "/images/badges/captain.png?v=6",
    description: "팀 주장 선정",
    unlockCondition: "팀 주장 임명",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "champion",
    name: "우승",
    icon: "🥇",
    imageUrl: "/images/badges/champion.png?v=6",
    description: "시즌 우승 달성",
    unlockCondition: "시즌 우승",
    maxProgress: 1,
    category: "field",
  },
  {
    id: "goal_machine",
    name: "득점 기계",
    icon: "🔥",
    imageUrl: "/images/badges/goal_machine.png?v=6",
    description: "시즌 10골 이상 기록",
    unlockCondition: "시즌 10골",
    maxProgress: 10,
    category: "field",
  },
  {
    id: "match_winner",
    name: "결승골",
    icon: "⚡",
    imageUrl: "/images/badges/match_winner.png?v=6",
    description: "결승전 골 기록",
    unlockCondition: "결승전 득점",
    maxProgress: 1,
    category: "field",
  },

  // ===== 골키퍼 전용 뱃지 =====
  {
    id: "clean_sheet",
    name: "클린시트",
    icon: "🧤",
    imageUrl: "/images/badges/clean_sheet.png?v=6",
    description: "골키퍼 무실점 3회 달성",
    unlockCondition: "클린시트 3회 (GK)",
    maxProgress: 3,
    category: "goalkeeper",
  },
  {
    id: "save_king",
    name: "세이브왕",
    icon: "🧱",
    imageUrl: "/images/badges/save_king.png?v=6",
    description: "시즌 최다 선방",
    unlockCondition: "시즌 선방 1위 (GK)",
    maxProgress: 1,
    category: "goalkeeper",
  },

  // ===== 심판 전용 뱃지 =====
  {
    id: "trusted_whistle",
    name: "신뢰의 휘슬",
    icon: "👁️",
    imageUrl: "/images/badges/trusted_whistle.png?v=6",
    description: "심판 평가 최고점",
    unlockCondition: "심판 평가 만점",
    maxProgress: 1,
    category: "referee",
  },
  {
    id: "gentle_referee",
    name: "매너 심판",
    icon: "✋",
    imageUrl: "/images/badges/gentle_referee.png?v=6",
    description: "매너 심판 선정",
    unlockCondition: "매너 심판 3회",
    maxProgress: 3,
    category: "referee",
  },
  {
    id: "honest_call",
    name: "정직한 판정",
    icon: "📋",
    imageUrl: "/images/badges/honest_call.png?v=6",
    description: "정직한 셀프 판정",
    unlockCondition: "셀프 파울 인정 5회",
    maxProgress: 5,
    category: "referee",
  },
  {
    id: "veteran_ref",
    name: "베테랑 심판",
    icon: "⏱️",
    imageUrl: "/images/badges/veteran_ref.png?v=6",
    description: "심판 경력 20경기 이상",
    unlockCondition: "심판 20경기",
    maxProgress: 20,
    category: "referee",
  },
];
